apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution: 
      - weight: 1 
        preference:
          matchExpressions:
          - key: spot 
            operator: In 
            values:
            - "yes"
  containers:
  - name: with-node-affinity
    image: docker.io/ocpqe/hello-pod